version: "3"

services:
  db:
    image: postgres:13-alpine
    environment: 
      - POSTGRES_DB=pos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - pos-data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pos:/pos
    ports:
      - "8000:8000"
    depends_on: 
      - db

volumes:
  pos-data:
