# Generated by Django 3.2.3 on 2021-05-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter membership type (e.g. Associate, Full, etc.)', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='suffix',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefix',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='member_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.membertype'),
        ),
    ]
