# Generated by Django 3.2.3 on 2021-05-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210526_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membertype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='member_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.membertype'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefix',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='suffix',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
