# Generated by Django 3.2.3 on 2021-05-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210526_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberType',
            new_name='MembershipType',
        ),
    ]
